### ISSUE TITLE
Show timestamp in UTC?

### ISSUE THREAD

**Issue by NikoKrause** [clefebvre/cinnamon-spices#14]
Wie have a versioning for xlets now (every commit is a new version).
To reflect this I created this PR https://github.com/linuxmint/Cinnamon/pull/6372
It shows the timestamp of the last commit in the About... Dialog of applets and desklets.
The extensions and themes don't have an About... Dialog, I think.
Not sure how/where to present this info.

If this gets merged info Cinnamon:
It would be great, if the last-edited timestamp would be shown on the spices website in UTC as well.
So users could press the "More info" button and could easily compare their version with the latest version on the spices website.

**Comment by NikoKrause** [comment]
@MrElectroNick 
The About dialog of spices shows the timestamp in UTC now in Cinnamon 3.4.
Also @collinss revamped the settings of spices, so in Cinnamon 3.6 it will be possible to show the About dialog of extensions and themes as well through settings.

It would be great, if we could show the timestamp of the last commmit in the same format as in the about dialog of the spices, so people can click the more info button in the about dialog and compare the timestamps easily.

**Comment by nyrrad** [comment]
I'll look into it for you @NikoKrause. Should be pretty easy to implements

**Comment by collinss** [comment]
@NikoKrause not themes. The about dialog is only available from the page that manages installed extensions, and that is not used in the theme settings.

**Comment by NikoKrause** [comment]
Ah. Sorry my bad.

**Comment by nyrrad** [comment]
The only foreseeable problem is how the spices are pulled into the database. It could lead to times being off for a small amount of time. It should be minimal though.

**Comment by NikoKrause** [comment]
You mean the timestamp would differ?
I'm not sure, how/where the timestamp is added anyway. There'd also another open issue here, that when you download a spice manually by clicking on the Download button, the spice does not contain the timestamp.

**Comment by nyrrad** [comment]
![utc](https://user-images.githubusercontent.com/12882579/29497269-eab36ace-85aa-11e7-8e55-5d4b061ed633.png)

What do you think about this as a compromise? 
It keeps the relative time there but if you want to compare timestamps, its there in UTC

I'm trying to roll this into an update that also resolves issue https://github.com/clefebvre/cinnamon-spices/issues/2 as well.

**Comment by NikoKrause** [comment]
Will it be obvious, that the UTC is available on hover?
I just noticed, that there is a tolltip, if you hover over the hour. Haven't seen it before.

I'm not entirely sure, but if you think that's a good compromise, then I'm ok with it.

**Comment by NikoKrause** [comment]
As @piiit mentionen in #2: The commit has is not meaningful, maybe you replace the has with the UTC timestamp?

**Last commit:** [[2017-08-20 04:21 UTC](https://github.com/linuxmint/cinnamon-spices-applets/commits/master/a4techTool@mous)] a4techTool@mous: Create da.po (#979)

**Comment by NikoKrause** [comment]
@nyrrad 
> The only foreseeable problem is how the spices are pulled into the database. It could lead to times being off for a small amount of time. It should be minimal though.

If you hover over the `Last edited: 1 month ago` on the spices website there appears the timestamp. That's the same timestamp, which is used for the About dialog of the spices. So you can use that to calculate/show the UTC time. (This timestamp is a little bit off to the one on GitHub itself. But it doesn't matter, because only thing that matters is, that it shows the same on the spices website and in the About dialog of the spice. I checked a few and the tooltip shows the correct timestamp of the spice.)

**Comment by nyrrad** [comment]
@NikoKrause how are you getting to this about dialogue? everything i click on just brings me to the spices website. I recently pushed an update to the import scripts on the server that uses the ACTUAL commit time of the commit rather than an arbitrary unix_timestamp() like it was... You saying they use the same thing right now has me wondering how it works for the cinnamon de itself.

**Comment by NikoKrause** [comment]
If you add an applet to the panel or a desklet to the desktop, you right click on the applet/desklet and then click `About ...` in the context menu:
![screenshot-area-2017-08-21-185346](https://user-images.githubusercontent.com/8415124/29529989-26e0c06c-86a2-11e7-9baf-c9db0a321c40.png)
The Dialog pops up in the center of your screen:
![screenshot-area-2017-08-21-185523](https://user-images.githubusercontent.com/8415124/29530045-64454bda-86a2-11e7-9369-ccccd5b0eb94.png)

Hovering over the same spice on the website, shows the tooltip:
![screenshot-area-2017-08-21-185651](https://user-images.githubusercontent.com/8415124/29530095-93e07a22-86a2-11e7-8751-923359a7347c.png)

The about dialog says: `2017-06-25 17:10:06 UTC`
And the tooltip says: `2017-06-25 18:10 UTC`

Exactly 1 hour difference, because it shows the local time (what's not entirely correct, it should be 2 hour difference, but I guess that's a bug on converting the time)

Cinnamon does it like [this](https://github.com/linuxmint/Cinnamon/pull/6372/files#diff-a2ef65ce9201d7e65190bc0b1d88f5a5R494), i.e. it uses the `last_edited` timestamp and converts it to UTC.

P.S.: We can remove the seconds in the UTC date.

**Comment by collinss** [comment]
Just an fyi, the about dialog gets the timestamp from the spices website when the cache is refreshed, so as long as the cache is up to date, the timestamps should always match. The issue comes if the user installs or updates without refreshing the cache. This can potentially lead to a situation where the applet is up to date, but the timestamps say otherwise.

**Comment by nyrrad** [comment]
@NikoKrause I believe the times are off because the site is probably running under the GMT timezone not UTC so it is being affected by day light savings time. This can be changed in the site configs, so the problem shouldn't persist for too terribly long.

As for the time stamp instead of the hash, I think the shortened hash should be there as it gives another comparative symbol. I have however changed the Time stamp to appear when you mouse over any of the commit info, so it will be rather hard to miss.

> P.S.: We can remove the seconds in the UTC date.
This is being done on cinnamons end.

@collinss Thanks for the info. Thats makes it pretty easy to keep it synced minus user error, but theres not a lot that can be done with that haha.

**Comment by NikoKrause** [comment]
I can remove the seconds in Cinnamons side. I just squash it into an open PR of mine.

**Comment by collinss** [comment]
It would be nice if we could add the timestamp to the metadata when an applet is downloaded, so that even if the cache is not up to date, the proper timestamp is given in the about dialog. Also, another issue that I forgot to mention with installing from an incorrect timestamp is that once the cache is updated it will show an update for the applet, even if there isn't one. These problems are somewhat mitigated in the next version of Cinnamon as opening the download page in settings will ask the user if they want to refresh the cache if it's been at least a week. Still, I think if we are using the timestamp for versioning, we should make sure we are shipping an applet with the correct one rather than relying on the cache which may or may not have up to date information.

**Comment by nyrrad** [comment]
@collinss
is this metadata.json uniform across applets/desklets/extensions/themes? 
I'm looking at the cinnamon code right now, does it simply skip the _load_metadata step if there isn't one, or does it try to retrieve it from somewhere else?

Right now the import scripts for the site, don't do anything but zip the files/uuid directory. I can write something that updates the metadata.json with the last_edited time stamp or create a metadata.json if it isn't one, but i need to know what mandatory info other than the last_edited (uuid? author?) i should put in there if the latter.

**Comment by collinss** [comment]
Themes don't currently need to have metadata.json, but everything else does. Uuid is currently a required field in that file. Author isn't required, but some of them have it already, and none of them currently have last_edited because it's added by cinnamon settings at the time of download.

**Comment by NikoKrause** [comment]
@nyrrad 
I created a PR to remove the seconds in the About dialog: https://github.com/linuxmint/Cinnamon/pull/6808/files

It looks like this now:
![screenshot-area-2017-08-22-100024](https://user-images.githubusercontent.com/8415124/29554819-dce4beee-8720-11e7-971b-8c963e714160.png)

**Comment by nyrrad** [comment]
@NikoKrause I pushed a fix, All times should now be displayed as UTC on the site. We're pushing from staging to prod tomorrow. Should show up then

**Comment by NikoKrause** [comment]
Cool. Can't wait

**Comment by NikoKrause** [comment]
I'm on cinnamon-spices-master right now. I like the hover for the timestamp.

But there's one change I don't like:
Hitting the Last commit link brings you to the [github commits](https://github.com/linuxmint/cinnamon-spices-applets/commit/4af8a4f122325a8cb3e52f69a58ba6b53faf6ae8) site. It used to link to the [spices history page](https://github.com/linuxmint/cinnamon-spices-applets/commits/master/CinnVIIStarkMenu@NikoKrause), which is more useful than going to only this one last commit. Can we change this back?

**Comment by nyrrad** [comment]
@NikoKrause reverted back to commit tree.

**Comment by NikoKrause** [comment]
Thanks!
